@startuml state
hide empty description
state "LoggedIn" as li{

    state "Unsynced" as li_uns{
        state "①doing task unsynced" as dtus
        state "③end task unsynced" as etus

    }
    state Synced{
        state "②doing task synced" as dts
        state "④end task synced" as ets

    }
    [*] -[#green]-> dtus: STARTボタンクリック
    [*] -[#green]-> dts
    [*] -[#blue]-> dts: 周期処理
    dts --> ets
    dts -[#blue]-> ets: 周期処理
    dtus --> etus

    dts --> etus
    dtus --> ets

    dtus -r[#blue]-> dts: 周期処理
    etus -r[#black]-> ets: (①から)Syncボタンクリック
    etus -r[#blue]-> ets: (②から)周期処理

}
state "Not LoggedIn" as nli{
    state "Unsynced" as nli_uns{
        state "doing task unsynced" as nli_dtus
        state "end task unsynced" as nli_etus
    }
    nli_dtus --> nli_etus: ENDボタンクリック
}

li -l[#black]-> nli: Log Out
nli -r[#black]-> li: Authorize

state "凡例" as legend {
    a:  
    b:  
    a -r[#green]-> b: STARTボタンクリック
    a -r-> b: ENDボタンクリック
    a -r[#blue]-> b: 周期処理
    
}

nli -[#transparent]-> legend

@enduml